### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by domoritz** [vega/svelte-vega#11]

**Comment by Sparkier** [comment]
Need @cabreraalex for this.

**Comment by cabreraalex** [comment]
My bad, I'll add ya'll - @Sparkier do you have an NPM account?

**Comment by domoritz** [comment]
Add me and we can set up auto deployments from ci. I'm domoritz.

**Comment by cabreraalex** [comment]
Added!

**Comment by domoritz** [comment]
Thanks. I set up #17

**Comment by domoritz** [comment]
I will make a release once #20 and #4 are resolved.

**Comment by domoritz** [comment]
Done: https://www.npmjs.com/package/svelte-vega
