### ISSUE TITLE
Build types and add them to the bundle

### ISSUE THREAD

**Issue by domoritz** [vega/svelte-vega#16]

**Comment by Sparkier** [comment]
Isn't this already there? I don't know if I get it.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/5690524/116540982-2830cd80-a8eb-11eb-973b-9f47700c1aa5.png">

**Comment by domoritz** [comment]
Ahh, I somehow saw a type error when I ran `lerna run validate` yesterday.
