### ISSUE TITLE
Page stops working after adding import statement

### ISSUE THREAD

**Issue by EmilyCheoh** [vega/svelte-vega#210]
Hi! I'm trying to set up a project using vega-lite. After installing the packages and modifying the `rollup.config.js`, I got this error of `Uncaught TypeError: Cannot destructure property 'ANY' of 'require$$26' as it is undefined.` in my browser's console right after I add the line of `import { VegaLite } from "svelte-vega";`. I also had warnings of Circular dependencies and `this has been rewritten to undefined`:

> (!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/fast-json-patch/module/helpers.mjs
4:  * MIT license
5:  */
6: var __extends = (this && this.__extends) || (function () {
                    ^
7:     var extendStatics = function (d, b) {
8:         extendStatics = Object.setPrototypeOf ||
...and 1 other occurrence
node_modules/vega-lite/build/src/compile/compile.js
1: var __rest = (this && this.__rest) || function (s, e) {
                 ^
2:     var t = {};
3:     for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p) && e.indexOf(p) < 0)
...and 1 other occurrence
node_modules/vega-lite/build/src/log/index.js
2:  * Vega-Lite's singleton logger utility.
3:  */
4: var __classPrivateFieldSet = (this && this.__classPrivateFieldSet) || function (receiver, state, value, kind, f) {
                                 ^
5:     if (kind === "m") throw new TypeError("Private method is not writable");
6:     if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a setter");
...and 3 other occurrences

I'm not sure what is happening and would really appeaciate any help or clarifications. Thanks in advance!

**Comment by domoritz** [comment]
Please update to the latest Vega-Lite and also see https://github.com/vega/svelte-vega/issues/90. Does that fix it?

**Comment by EmilyCheoh** [comment]
Thank you for your reply! My vega-lite is up-to-date and I was using rollup and copied the svelte-vega package's configuration code but still got the 

> `this` has been rewritten to `undefined`

error.

**Comment by domoritz** [comment]
That's a warning, not an error, no?

**Comment by EmilyCheoh** [comment]
Ah yes, sorry! The error I got is actually `[!] Error: You must specify "output.file" or "output.dir" for the build.` Do you think this is because I was using JavaScript instead of TypeScript as my rollup.config.js looks like this:
![image](https://user-images.githubusercontent.com/26803359/133499171-c3a9c126-5642-4cca-9450-6f838389ed0c.png)
Thanks!

**Comment by domoritz** [comment]
This sounds like an issue with your build config and not this project. I am closing this issue but am happy to reopen if you think that's a mistake.

**Comment by EmilyCheoh** [comment]
Thanks for your help!
