### ISSUE TITLE
Review utils

### ISSUE THREAD

**Issue by domoritz** [vega/svelte-vega#3]
See which ones we still need or which can be cleaned up.

**Comment by domoritz** [comment]
- [ ] Can we remove `combineSpecWithDimension`? I'm not clear what purpose it serves. 
- [ ] `updateMultipleDatasetsInView` only appears in Vega but not Vega-Lite. That seems suspicious as Vega-Lite compiles to  Vega. 
- [ ] `updateSingleDatasetInView` can probably be inlined since it's only used in a single method

I would combine all utils functions in a single file. There is no need to a file per perfection.

**Comment by Sparkier** [comment]
Regarding `updateMultipleDatasetsInView`, our `VegaLite` component simply sets the mode to `vega-lite`, and then renders a `Vega` component. Thus, this function gets called when something updates for both Vega and Vega-Lite.

**Comment by Sparkier** [comment]
Regarding `combineSpecWithDimension`, for vega-embed, the dimensions can be set in both the `VisualizationSpec` or the `EmbedOptions`. When the options change, we always recreate the view. However, we dont want to do that for a dimension change.
Thus, dimensions are handled in the spec changes. For ensuring that the dimensions in options are considered, we need to add those to the spec if applicable.

**Comment by domoritz** [comment]
> Regarding `updateMultipleDatasetsInView`, our `VegaLite` component simply sets the mode to `vega-lite`, and then renders a `Vega` component. Thus, this function gets called when something updates for both Vega and Vega-Lite.

I see. Does it make sense to move the logic to the embed component then? This way the Vega and Vega-Lite component could almost just be aliases.

**Comment by domoritz** [comment]
> Regarding combineSpecWithDimension, for vega-embed, the dimensions can be set in both the VisualizationSpec or the EmbedOptions. When the options change, we always recreate the view. However, we dont want to do that for a dimension change.
Thus, dimensions are handled in the spec changes. For ensuring that the dimensions in options are considered, we need to add those to the spec if applicable.

I see. So it's a bit of a hack. We just want to make sure that no matter ow dimensions are specified, we don't re-create a view if that's the only thing that changes.

**Comment by Sparkier** [comment]
> > Regarding combineSpecWithDimension, for vega-embed, the dimensions can be set in both the VisualizationSpec or the EmbedOptions. When the options change, we always recreate the view. However, we dont want to do that for a dimension change.
> > Thus, dimensions are handled in the spec changes. For ensuring that the dimensions in options are considered, we need to add those to the spec if applicable.
> 
> I see. So it's a bit of a hack. We just want to make sure that no matter ow dimensions are specified, we don't re-create a view if that's the only thing that changes.

Yes it kind of is a hack to make things easier when comparing states. Do you want that to be changed or should we leave it?

**Comment by domoritz** [comment]
I think dimensions are important enough (and cause issues like https://github.com/vega/svelte-vega/issues/6) that we should think about this a bit.

**Comment by domoritz** [comment]
Let's close this once you removed combineSpecWithDimension @Sparkier

**Comment by Sparkier** [comment]
I may have misunderstood, but I thought I should only move `updateMultipleDatasesInView`. I thought we wanted to keep combineSpecWithDimension for keeping the rerender decision simpler.

**Comment by domoritz** [comment]
Discussed and sounds good.
