### ISSUE TITLE
When the data in spec changes, the view does not update.

### ISSUE THREAD

**Issue by Sparkier** [vega/svelte-vega#32]
If the data that is embedded into spec changes (not any of the keys in data), the view does not update.

**Comment by domoritz** [comment]
What was the resolution here?

**Comment by Sparkier** [comment]
I had another issue which made me think this was the case, but I think it is not as I thought.
This is the check if those spec fields are equal (including the data):
```js
     fieldNames.some(
      (field) =>
        !(field in newSpec) ||
        !(field in oldSpec) ||
        !equal(
          newSpec[field as keyof typeof newSpec],
          oldSpec[field as keyof typeof oldSpec]
        )
    )
```

**Comment by Sparkier** [comment]
I think my problem was specifically related to the way I feed arrow data to `svelte-vega`.
