### ISSUE TITLE
Review Svelte API

### ISSUE THREAD

**Issue by domoritz** [vega/svelte-vega#4]

**Comment by domoritz** [comment]
One big question for me is error handling. @cabreraalex should we catch errors and provide a handler or just let error bubble up? For example in https://github.com/vega/svelte-vega/blob/7a6315f0846610908f00f79be0fb5beda6632213/packages/svelte-vega/src/VegaEmbed.svelte#L110

**Comment by cabreraalex** [comment]
Does it use promises? There is built-in error handling for async calls: https://svelte.dev/tutorial/await-blocks

**Comment by cabreraalex** [comment]
I guess there's no de-facto way to do real try blocks: https://github.com/sveltejs/svelte/issues/3733

**Comment by cabreraalex** [comment]
LGTM, two thoughts:
1. Does it make sense to just have one `Vega` component? the vega-embed API doesn't distinguish between vega and vegalite, can take either in and figure out which it is.
2. I think bubbling up errors to the user in promises is too confusing. If anything, we could have an "error" component that shows a red message when it fails to render. Right now it's just blank. Or let people pass in slots or a custom component to show on error. idk, lots of ways to do it, it's fine as is though

**Comment by domoritz** [comment]
We have a Vega-Embed component. The advantage of Vega/Vega-Lite components is that they set the `mode`. I think that can be useful. Maybe we could expose the `VegaEmbed` component? 

The advantage of a pure Vega component could be that we skip the Vega-Lite import (not sure whether we are doing that right now but we could).

**Comment by domoritz** [comment]
I'm surprised there is no proper/standard error handling in Svelte. If you think what we have is okay for now, let's release.

**Comment by cabreraalex** [comment]
Go for it!
