### ISSUE TITLE
Svelte component does not export VisualizationSpec

### ISSUE THREAD

**Issue by cabreraalex** [vega/svelte-vega#55]
To not have to import `Vega-embed`, we should export the interface for VisualizationSpec, it's currently not included in the index file.

**Comment by cabreraalex** [comment]
I think this is a VSCode error, it is exported but not detected by VSCode:

<img width="604" alt="Screen Shot 2021-05-19 at 3 20 24 PM" src="https://user-images.githubusercontent.com/4563691/118892434-bdedc600-b8b5-11eb-94d0-0fa54c456bc1.png">

**Comment by domoritz** [comment]
We need to add the extra export to the index.ts file then.

**Comment by domoritz** [comment]
Oh weird, we do that already in https://github.com/vega/svelte-vega/blob/59833d58a2f63511dc0a0498b049b5714c426044/packages/svelte-vega/src/index.ts#L3

**Comment by cabreraalex** [comment]
I think the new version isn't on NPM

**Comment by domoritz** [comment]
Yep, done in https://github.com/vega/svelte-vega/commit/306d5f34605c88e2facce4c75dbcf8e979cdbc10.
