### ISSUE TITLE
Expose the Vega embed view for easier debugging

### ISSUE THREAD

**Issue by cabreraalex** [vega/svelte-vega#56]
Exposing the generated View from Vega-embed would allow for easier debugging and customization, e.g. https://vega.github.io/vega/docs/api/debugging/

**Comment by domoritz** [comment]
Isn't that what `onNewView` does? Is there a more Svelte way to expose the view?

**Comment by cabreraalex** [comment]
I was thinking of exposing it as a prop, then you can do bind:vegaView={view} and get a reactive variable for it

**Comment by cabreraalex** [comment]
Something like this: https://svelte.dev/tutorial/component-bindings .

**Comment by domoritz** [comment]
I like that. Go for it.

**Comment by cabreraalex** [comment]
What's better to expose, View or Result?

**Comment by domoritz** [comment]
Note that the view is not just useful for debugging but also for generating images etc.

**Comment by domoritz** [comment]
Result wraps view, the compiled Vega spec (https://github.com/vega/vega-embed/blob/87c1bca275e5d5f7697a03d0e3ec3429b68fc495/src/embed.ts#L127), and finalize (which we don't need). I would say, let's expose View and maybe the compiled Vega spec later.
