### ISSUE TITLE
Resize not working properly

### ISSUE THREAD

**Issue by Sparkier** [vega/svelte-vega#6]
In the storybook example which changes the chart size (`packages/storybook/stories/ChangingDimensionDemo.svelte`), resizing does not work correctly. While the axes resize correctly, the marks do not resize. This bug likely exists  not only in this example.

**Comment by Sparkier** [comment]
@domoritz do you have an idea on this? I thought doing `view.height()` and `view.runAsync()` would be enough to handle this.

**Comment by domoritz** [comment]
Looks like it's an issue with Vega

<img width="1825" alt="Screen Shot 2021-04-29 at 09 05 12" src="https://user-images.githubusercontent.com/589034/116582242-03782e00-a8ca-11eb-99b2-7e8db9ef69d9.png">
