### ISSUE TITLE
Support Svelte 4

### ISSUE THREAD

**Issue by robwiegman-profit4cloud** [vega/svelte-vega#858]
- [x] Check for duplicate issues. Please file separate requests as separate issues on GitHub.
- [x] Clearly describe the goal of the feature request. Why is it needed?
- [x] Describe an envisioned solution. What do you want the new behavior to be?
- [x] If applicable, share mockup images or links to examples illustrating the desired output.

**Goal**
Ability to use `svelte-vega` as a dependency in a project that uses Svelte 4.x.x. 

**Description**
[Svelte 4 has been released on 22-06-2023.](https://svelte.dev/blog/svelte-4)
In my project, when I update to `"svelte": "^4.0.4"`, I get an error when running `npm install` stating that the dependencies cannot be resolved because `svelte-vega` (I'm on 2.0.0) requires a different version of Svelte.

Can you please update?

I think, the problem is here:
- https://github.com/vega/svelte-vega/blob/main/packages/svelte-vega/package.json#L67C14-L67C21
- https://github.com/vega/svelte-vega/blob/main/packages/svelte-vega/package.json#L60

**Comment by domoritz** [comment]
Can you send a pull request?

**Comment by paulogonc** [comment]
Any news on that issue? I also get this error while trying to use it in combination with svelte 4. Thanks

**Comment by domoritz** [comment]
See #859

**Comment by liamdiprose** [comment]
@paulogonc I was able to remove the error with an override in `package.json`:

```js
{
  "dependencies": {},
  "overrides": {
    "svelte-vega": {
      "svelte": "^4.0.0"
    }
  }
}

```

**Comment by paulogonc** [comment]
@liamdiprose thanks for the hint, now it works! :-)
