### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by davidhaley** [vega/svelte-vega#867]
![image](https://github.com/vega/svelte-vega/assets/11729897/20c9a25d-76d4-4914-bdf2-e2c73345d1a6)

![image](https://github.com/vega/svelte-vega/assets/11729897/3a096dc5-ff07-4b5f-847d-eec2522d7fc6)

**Comment by domoritz** [comment]
Thanks for the issue. I fixed it by uploading a `.nojekyll` file.
