### ISSUE TITLE
sveltekit complains about using synthentic commonjs import

### ISSUE THREAD

**Issue by t-samuelg** [vega/svelte-vega#868]
"svelte-vega": "^2.1.0",
"@sveltejs/kit": "^1.22.6",

```
import { vega } from "vega-embed";
         ^^^^
SyntaxError: Named export 'vega' not found. The requested module 'vega-embed' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vega-embed';
const { vega } = pkg;
```

see https://github.com/vega/svelte-vega/blob/acc0b2504f4a7e7a40020f695c7d0dd7c5defc9b/packages/svelte-vega/src/lib/utils.ts#L2

**Comment by domoritz** [comment]
Weird. Vega-Embed has a module export at https://github.com/vega/vega-embed/blob/b4ec77f7f4aa4a5573882c19d2e3d3715271a059/package.json#L32 so I think this is an issue with the bundler. Maybe it needs `type: module`. If you have a suggestion, let me know. Otherwise I'm not sure what to do.

**Comment by mkery** [comment]
Same issue here

**Comment by domoritz** [comment]
Related: https://github.com/vega/svelte-vega/issues/545 and https://github.com/sveltejs/kit/issues/5325.

I am confused since embed already has a module export and that should be the one used for esm packages. Unfortunately, different bundlers behave differently.

**Comment by domoritz** [comment]
The sveltekit example in https://github.com/vega/svelte-vega/pull/910 works. It does break when I update all the dependencies.

**Comment by domoritz** [comment]
It looks like the issue is vite 5. Please use vite 4 for now. At least that seems to fix it for me with the SvelteKit example in this repo.
