### ISSUE TITLE
version 2.3.0 not on npm

### ISSUE THREAD

**Issue by lkeegan** [vega/svelte-vega#974]
The latest version on npm is 2.2.1

Would it be possible to add version 2.3.0?

It looks like there was an issue with the publish CI job ("Found 0 commits since last release"):
https://github.com/vega/svelte-vega/actions/runs/11733952881/job/32689146273#step:5:37

Thanks for this very nice library!

**Comment by domoritz** [comment]
Released.

**Comment by lkeegan** [comment]
thanks!
